# Site settings
title: '🛠  Beauty In Code 202  🛠'
baseurl: ''
url: 'https://beautyincode.se'
permalink: 'pretty'

# Google Analytics tracking code
# analytics: 'UA-113788547-1'

# Jekyll plugins
plugins:
  - 'jekyll-tidy'

# Server settings
host: 0.0.0.0
port: 5006

# Exclude
exclude:
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE'
  - 'README.md'
  - 'node_modules'
  - 'package.json'
  - 'postcss.*.js'
  - 'scripts'
  - 'src'
  - 'svg-sprite.config.json'
  - 'yarn.lock'
  - 'Dockerfile'
  - 'docker-compose.yml'
  - 'docker-compose.prod.yml'
