version: '3'

services:

  jekyll:
    container_name: bic-jekyll

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - $PWD:/srv/jekyll

    working_dir: /srv/jekyll

    environment:
      NODE_ENV: development
      JEKYLL_ENV: development

    ports:
      - '5005:5005'

    command: yarn start
