name: Deploy 🚀

on:
  push:
    branches:
      - master

  # pull_request:
  #   branches:
  #     - master

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install Yarn packages
        run: yarn install --production

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      # - name: Set up Ruby 2.4
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: 2.4.x
      #
      # - name: Bundle install
      #   run: |
      #     gem install bundler
      #     bundle install --jobs 4 --retry 3
      #
      # - name: Jekyll build
      #   run: jekyll build --config "_config.yml,_config.prod.yml"

      - name: Jekyll build
        uses: docker://jekyll/jekyll
        with:
          args: /bin/sh -c "jekyll build --config \"_config.yml,_config.prod.yml\""

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: _site
