name: Deploy to Github Pages

on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Spin up Docker container
        run: docker-compose -f docker-compose.prod.yml up

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: _site
