name: stylelint

on:
  pull_request:
    branches:
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: stylelint
        uses: actions-hub/stylelint@v1.1.2
        env:
          PATTERN: 'src/css/*.css'
